apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-demo-application
  namespace: gitops
spec:
  project: default

  source:
    repoURL: https://github.com/BaruchBazakDev/demo-app-gitops.git
    targetRevision: HEAD
    path: demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

