apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
stringData:
  {{- with .Values.secrets }}
  MONGO_URI: {{ .mongodbUri }}
  MONGO_USERNAME: {{ .mongodbUserName }}
  MONGO_PASS: {{ .mongodbPass }}
  {{- end }}
